### ISSUE TITLE
"Network access is disabled" after wakeup

### ISSUE THREAD

**Issue by AcarBurak** [eteran/qgmailnotifier#5]
This has started to happen after an upgrade in Arch, but I don't know with which updated package qgmailnotifier conflicts. Same issue with both the latest AUR (from git) and the previous one. Need to relaunch qgmailnotifier after every wakeup.

**Comment by eteran** [comment]
Can you elaborate by what you mean "conflicts"? When I think of a conflicting package, I think about compile issues. But the rest of your issue sounds like a runtime problem.

What exactly is the issue? That after a resume from suspend, qgmailnotifier can no longer connect to gmail; and that exiting it and running it again resumes functionality?

If we can narrow down what the issue is, I'll be happy to try to work it out. However, it is possible that it is due to something external to qgmailnotifier. We'll try :-)

**Comment by AcarBurak** [comment]
Very sorry. Well, I mean, I've been using qgmailnotifier without any issue, but then some time ago (probably after an update of some system packages) it's started to behave like that. Yes, I resume from suspend, but qgmailnotifier can't make a connection saying "Network access is disabled", though it's not disabled. By quiting and relaunching it everything returns to normal, it works again.

By the way, I use connmann on Arch, if it's relevant.

**Comment by AcarBurak** [comment]
Sorry to bother you; the issue seems to be fixed with the latest Qt update to 5.5.1-2.

**Comment by AcarBurak** [comment]
Sorry again, not solved by the Qt update.

**Comment by eteran** [comment]
No worries. If someone else encounters this issue, then they'll be able to find the solution a little quicker :-)

**Comment by eteran** [comment]
Hmm, looking at the code for qgmailnotifier. I have no idea why it would be sensitive to suspend/resume :-/. It still may be a bug in Qt itself.

**Comment by AcarBurak** [comment]
Thanks for your concern eteran. Well, I've tried another notifier (https://github.com/mhogomchungu/qCheckGMail) and it has the same issue, but another one (https://github.com/rinaldus/mail-notifier) doesn't have it, it works.

Either a Qt or another system update should've caused it, but I don't have any idea.

**Comment by eteran** [comment]
So, both qCheckGMail and qgmailnotifier use `QNetworkRequest` and related (Qt's method for making network requests). 

mail-notifier, using a python imap library. So a couple of data points here:

1. mail-notifier uses the IMAP API, not the native gmail one. If that fits your needs, it should work well.
2. The problem **seems** to be Qt related since two unrelated projects using the same methodology encounter the same issue.

**Comment by AcarBurak** [comment]
All right; so when Qt's fixed...

**Comment by AcarBurak** [comment]
Well, Qt 5.5.1-3 has fixed it finally.

Qt has been updated several times within very short time periods, so it must have been a general issue causing this as well.

**Comment by eteran** [comment]
Glad that you got it all sorted out :-)

**Comment by AcarBurak** [comment]
Thank you. The fruit of persevering!
